'use client';

import { useState } from 'react';
import { NFL_TEAMS } from '../data/teams';
import type { DraftPick } from './PicksList';
import { pickValue, getGrade } from '../lib/grading';

function getPickGrade(pickNumber: number, playerGrade: number): { value: number; letter: string } {
  const value = pickValue(playerGrade, pickNumber);
  return { value, letter: getGrade(value).letter };
}

export function formatDraftText(picks: DraftPick[], userTeamAbbr: string | null): string {
  if (picks.length === 0) return '';

  const lines: string[] = [];

  // Header
  const rounds = new Set(picks.map((p) => p.round));
  lines.push(`🏈 2026 NFL Draft — ${rounds.size} Round${rounds.size > 1 ? 's' : ''}, ${picks.length} Picks`);

  if (userTeamAbbr) {
    const franchise = NFL_TEAMS.find((t) => t.abbr === userTeamAbbr);
    if (franchise) {
      lines.push(`GM Mode: ${franchise.city} ${franchise.name}`);
    }
  }

  // All picks grouped by round
  const sorted = [...picks].sort((a, b) => a.pickNumber - b.pickNumber);
  const byRound = new Map<number, DraftPick[]>();
  for (const pick of sorted) {
    const existing = byRound.get(pick.round) ?? [];
    existing.push(pick);
    byRound.set(pick.round, existing);
  }

  for (const [round, roundPicks] of byRound) {
    lines.push('');
    lines.push(`── Round ${round} ──`);
    for (const pick of roundPicks) {
      lines.push(
        `#${pick.pickInRound} ${pick.teamAbbr} — ${pick.player.name} (${pick.player.position}, ${pick.player.school})`
      );
    }
  }

  // User picks section
  if (userTeamAbbr) {
    const userPicks = sorted.filter((p) => p.teamAbbr === userTeamAbbr);
    if (userPicks.length > 0) {
      lines.push('');
      lines.push('📊 My Picks:');
      for (const pick of userPicks) {
        const { letter } = getPickGrade(pick.pickNumber, pick.player.grade);
        lines.push(
          `R${pick.round}#${pick.pickInRound} — ${pick.player.name} (${pick.player.position}, ${pick.player.school}) — Grade: ${letter}`
        );
      }
    }
  }

  lines.push('');
  lines.push('Generated by On The Clock | demos.aicoderally.com');

  return lines.join('\n');
}

interface DraftExportProps {
  picks: DraftPick[];
  userTeamAbbr: string | null;
}

export default function DraftExport({ picks, userTeamAbbr }: DraftExportProps) {
  const [copied, setCopied] = useState(false);

  async function handleCopy() {
    const text = formatDraftText(picks, userTeamAbbr);
    if (!text) return;

    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    } catch {
      // Fallback for older browsers
      const textarea = document.createElement('textarea');
      textarea.value = text;
      textarea.style.position = 'fixed';
      textarea.style.opacity = '0';
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand('copy');
      document.body.removeChild(textarea);
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    }
  }

  return (
    <button
      onClick={handleCopy}
      disabled={picks.length === 0}
      className={`inline-flex items-center gap-1.5 px-3 py-1.5 rounded text-xs font-bold transition-all ${
        copied
          ? 'bg-emerald-500/20 text-emerald-400'
          : picks.length === 0
            ? 'bg-white/5 text-slate-600 cursor-not-allowed'
            : 'bg-amber-500/15 text-amber-400 hover:bg-amber-500/25 hover:text-amber-300'
      }`}
    >
      {copied ? (
        <>
          {/* Checkmark icon */}
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
            <polyline points="20 6 9 17 4 12" />
          </svg>
          Copied!
        </>
      ) : (
        <>
          {/* Clipboard icon */}
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
            <rect x="9" y="2" width="6" height="4" rx="1" />
            <path d="M9 4H7a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V6a2 2 0 0 0-2-2h-2" />
          </svg>
          Share Draft
        </>
      )}
    </button>
  );
}
