'use client';

import { useState, useCallback } from 'react';
import { AI_RESPONSES } from '@/data/lotos';
import { MarkdownRenderer, Toast } from '@/components/demos/lotos';

const marketBriefs = AI_RESPONSES.filter((r) => r.category === 'market-intel');

const KEY_METRICS = [
  { label: 'Price Trend', value: '-1.2%', detail: 'Week-over-week', color: '#DC2626', bg: '#FEF2F2' },
  { label: 'Inventory Level', value: '+8%', detail: 'Area dealers', color: '#D97706', bg: '#FFFBEB' },
  { label: 'Gross / Unit', value: '$4,650', detail: 'vs $4,000 target', color: '#16A34A', bg: '#F0FDF4' },
];

const ACTION_ITEMS = [
  {
    priority: 'HIGH',
    priorityColor: '#DC2626',
    priorityBg: '#FEF2F2',
    title: 'Auction Opportunity',
    detail: 'Manheim Phoenix Thursday sale has 40+ Toyota/Honda units — your fastest-turning brands.',
  },
  {
    priority: 'HIGH',
    priorityColor: '#DC2626',
    priorityBg: '#FEF2F2',
    title: 'Price Adjustment Needed',
    detail: 'STK-005 and STK-010 are 60+ days. Drop asking price 8-10% or wholesale this week.',
  },
  {
    priority: 'MED',
    priorityColor: '#D97706',
    priorityBg: '#FFFBEB',
    title: 'F&I Push',
    detail: 'Penetration at 70% — strong. New maintenance plan (FNI-006) is driving incremental $795/deal.',
  },
];

export default function MarketIntelPage() {
  const [briefIndex, setBriefIndex] = useState(0);
  const [toastMsg, setToastMsg] = useState<string | null>(null);
  const [checkedItems, setCheckedItems] = useState<boolean[]>(ACTION_ITEMS.map(() => false));

  const currentBrief = marketBriefs[briefIndex % marketBriefs.length];

  const handleGenerateNew = useCallback(() => {
    setBriefIndex((prev) => (prev + 1) % marketBriefs.length);
  }, []);

  const handleShare = useCallback(() => {
    if (currentBrief) {
      navigator.clipboard.writeText(currentBrief.answer).catch(() => {});
      setToastMsg('Brief copied to clipboard');
    }
  }, [currentBrief]);

  const toggleCheck = useCallback((idx: number) => {
    setCheckedItems((prev) => {
      const next = [...prev];
      next[idx] = !next[idx];
      return next;
    });
  }, []);

  const briefTitle = currentBrief?.question === 'Weekly market brief'
    ? 'Weekly Market Brief — April 1, 2026'
    : currentBrief?.question === 'Weekly market brief (Mar 25)'
    ? 'Weekly Market Brief — March 25, 2026'
    : 'Weekly Market Brief — March 18, 2026';

  return (
    <div className="lot-page" style={{ padding: '24px' }}>
      <div className="space-y-6">
        {toastMsg && <Toast message={toastMsg} onDismiss={() => setToastMsg(null)} />}

        <div className="flex items-start justify-between">
          <div>
            <h1 className="lot-heading">
              Market Intelligence
            </h1>
            <p className="lot-description">
              Weekly AI-generated brief — Phoenix Metro used vehicle market
            </p>
          </div>
          <div className="flex gap-2">
            <button
              onClick={handleShare}
              className="lot-btn"
            >
              Share Brief
            </button>
            <button
              onClick={handleGenerateNew}
              className="rounded-xl px-4 py-2 text-sm font-bold"
              style={{ backgroundColor: '#DC2626', color: '#FFFFFF' }}
            >
              Generate New Brief
            </button>
          </div>
        </div>

        <div
          className="rounded-xl px-6 py-4 flex items-center justify-between"
          style={{ backgroundColor: '#FEF2F2', border: '1px solid #FECACA' }}
        >
          <div className="flex items-center gap-3">
            <div
              className="w-10 h-10 rounded-full flex items-center justify-center font-black text-base"
              style={{ backgroundColor: '#DC2626', color: '#FFFFFF' }}
            >
              AI
            </div>
            <div>
              <p className="text-base font-bold" style={{ color: 'var(--lot-text)' }}>{briefTitle}</p>
              <p className="text-sm" style={{ color: 'var(--lot-text-muted)' }}>Generated by AskLotOS AI · Phoenix Metro · Sora Auto · Brief {briefIndex + 1} of {marketBriefs.length}</p>
            </div>
          </div>
          <div
            className="flex items-center gap-2 rounded-full px-3 py-1.5 text-xs font-bold"
            style={{ backgroundColor: '#DCFCE7', color: '#15803D' }}
          >
            <span className="inline-block w-2 h-2 rounded-full" style={{ backgroundColor: '#16A34A' }} />
            Live
          </div>
        </div>

        <div className="grid grid-cols-1 gap-4 lg:grid-cols-4">
          <div className="lg:col-span-1 space-y-3">
            <h2 className="lot-subheading" style={{ fontSize: '16px' }}>Key Metrics</h2>
            {KEY_METRICS.map((metric) => (
              <div
                key={metric.label}
                className="rounded-xl border p-4 lot-animate-in"
                style={{ backgroundColor: metric.bg, borderColor: 'var(--lot-border)' }}
              >
                <p className="text-xs font-semibold uppercase tracking-wider" style={{ color: 'var(--lot-text-muted)' }}>{metric.label}</p>
                <p className="text-3xl font-black mt-1" style={{ color: metric.color }}>{metric.value}</p>
                <p className="text-xs mt-0.5" style={{ color: 'var(--lot-text-secondary)' }}>{metric.detail}</p>
              </div>
            ))}
          </div>

          <div className="lg:col-span-3 lot-card lot-animate-in">
            <MarkdownRenderer text={currentBrief?.answer ?? ''} />
          </div>
        </div>

        <div>
          <h2 className="lot-subheading" style={{ marginBottom: '12px' }}>Action Items</h2>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-3">
            {ACTION_ITEMS.map((item, i) => (
              <div
                key={i}
                className="lot-card lot-animate-in"
                style={{ padding: '20px' }}
              >
                <div className="flex items-center gap-2 mb-3">
                  <button
                    onClick={() => toggleCheck(i)}
                    role="checkbox"
                    aria-checked={checkedItems[i]}
                    aria-label={`Mark action ${i + 1} as ${checkedItems[i] ? 'incomplete' : 'complete'}`}
                    style={{
                      width: '20px',
                      height: '20px',
                      borderRadius: '4px',
                      border: checkedItems[i] ? '2px solid #16A34A' : '2px solid var(--lot-border)',
                      background: checkedItems[i] ? '#16A34A' : 'var(--lot-card)',
                      cursor: 'pointer',
                      display: 'flex',
                      alignItems: 'center',
                      justifyContent: 'center',
                      color: '#FFFFFF',
                      fontSize: '12px',
                      fontWeight: 700,
                      flexShrink: 0,
                    }}
                  >
                    {checkedItems[i] ? '\u2713' : ''}
                  </button>
                  <span
                    className="rounded-full px-2.5 py-0.5 text-xs font-bold"
                    style={{ backgroundColor: item.priorityBg, color: item.priorityColor }}
                  >
                    {item.priority}
                  </span>
                  <span className="text-xs font-semibold" style={{ color: 'var(--lot-text-muted)' }}>Action {i + 1}</span>
                </div>
                <p
                  className="text-base font-bold"
                  style={{
                    color: 'var(--lot-text)',
                    textDecoration: checkedItems[i] ? 'line-through' : 'none',
                    opacity: checkedItems[i] ? 0.6 : 1,
                  }}
                >
                  {item.title}
                </p>
                <p
                  className="text-sm mt-2 leading-relaxed"
                  style={{
                    color: 'var(--lot-text-secondary)',
                    opacity: checkedItems[i] ? 0.6 : 1,
                  }}
                >
                  {item.detail}
                </p>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
