// Re-export all types from the shared package
export type {
  Rule,
  PercentOfRule,
  FixedPerMatchRule,
  TieredRule,
  LookupRule,
  MultiplierRule,
  PlaceholderRule,
  BundleBonusRule,
  TierStep,
  ItemMatcher,
  RateTable,
  ClientConfig,
  ComponentConfig,
  SummaryMetricConfig,
  ThresholdConfig,
  MetricBasis,
  SaleItem,
  PeriodContext,
  CalculationResult,
  ComponentResult,
  ThresholdResult,
  SummaryMetricResult,
} from '@/lib/swic-engine';
