'use client';

import { useState } from 'react';
import { PhoenixPage } from '@/components/demos/phoenix-intel/PhoenixPage';
import { AIInsightCard } from '@/components/demos/phoenix-intel/AIInsightCard';
import { getInsight } from '@/data/phoenix-intel/ai-insights';
import { FileText, Sparkles, Clock } from 'lucide-react';

const REPORT_TYPES = [
  { id: 'iotd', name: "President's Intelligence of the Day", description: 'Daily briefing with pipeline movement, client health, and action items', frequency: 'Daily', lastGenerated: '2026-03-16', views: 22 },
  { id: 'monthly', name: 'Monthly Performance Report', description: 'Revenue, utilization, engagement progress, and financial projections', frequency: 'Monthly', lastGenerated: '2026-03-01', views: 8 },
  { id: 'pipeline', name: 'Pipeline Analysis Report', description: 'Deal stage analysis, conversion rates, and revenue forecasting', frequency: 'Weekly', lastGenerated: '2026-03-14', views: 12 },
  { id: 'client-health', name: 'Client Health Summary', description: 'Health scores, engagement status, and renewal opportunities', frequency: 'Monthly', lastGenerated: '2026-03-01', views: 6 },
  { id: 'assessment', name: 'Assessment Portfolio Report', description: 'Completed assessments, trends, and cross-client insights', frequency: 'Quarterly', lastGenerated: '2026-01-15', views: 4 },
  { id: 'training', name: 'Academy Analytics Report', description: 'Enrollment, completion rates, satisfaction scores, and revenue', frequency: 'Monthly', lastGenerated: '2026-03-01', views: 5 },
];

const SAMPLE_IOTD = `**President's Intelligence of the Day — March 16, 2026**

**Pipeline:**
- Mountain View Phase 2 ($95K) — contract signing expected today
- Green Valley ($85K) — proposal sent 6 days ago, follow-up recommended
- SafeHaven ($58K) — final scope meeting scheduled for March 20

**Client Health:**
- Heritage Arts (assessment 88% complete) — transition to renewal within 30 days
- Faith & Light (stewardship 82%) — approaching final deliverables

**Financial:**
- Q1 revenue: $246K (strongest quarter ever)
- YTD target tracking: 93% ($840K of $900K)

**Action Items:**
1. Call Green Valley — 6 days without follow-up on $85K proposal
2. Schedule Phase 2 kickoff with Mountain View after signing
3. Begin renewal conversation with Heritage Arts

*Generated by Phoenix Intel AI*`;

export default function ReportsPage() {
  const insight = getInsight('reports');
  const [selectedReport, setSelectedReport] = useState<string | null>(null);
  const [generating, setGenerating] = useState(false);

  const handleGenerate = (reportId: string) => {
    setGenerating(true);
    setSelectedReport(null);
    setTimeout(() => {
      setSelectedReport(reportId);
      setGenerating(false);
    }, 1500);
  };

  return (
    <PhoenixPage title="Reports" subtitle="AI-generated intelligence reports and analytics" accentColor="#3b6bf5">
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-8">
        {REPORT_TYPES.map(report => (
          <div key={report.id} className="phoenix-card">
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 8 }}>
              <div style={{ display: 'flex', gap: 10 }}>
                <FileText size={18} color="var(--pi-sapphire)" />
                <div>
                  <div style={{ fontSize: '0.9rem', fontWeight: 700, color: 'var(--pi-text)' }}>{report.name}</div>
                  <div style={{ fontSize: '0.875rem', color: 'var(--pi-text-muted)', marginTop: 2 }}>{report.description}</div>
                </div>
              </div>
            </div>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginTop: 12, paddingTop: 8, borderTop: '1px solid var(--pi-border-faint)' }}>
              <div style={{ display: 'flex', gap: 12, fontSize: '0.85rem', color: 'var(--pi-text-faint)' }}>
                <span><Clock size={10} style={{ display: 'inline', verticalAlign: 'middle' }} /> {report.frequency}</span>
                <span>Last: {report.lastGenerated}</span>
                <span>{report.views} views</span>
              </div>
              <button
                onClick={() => handleGenerate(report.id)}
                style={{
                  padding: '6px 12px', borderRadius: 6, border: 'none', background: 'var(--pi-sapphire)',
                  color: '#fff', fontSize: '0.85rem', fontWeight: 700, cursor: 'pointer',
                  display: 'flex', alignItems: 'center', gap: 4,
                }}
              >
                <Sparkles size={12} /> Generate
              </button>
            </div>
          </div>
        ))}
      </div>

      {/* Generated report preview */}
      {generating && (
        <div className="phoenix-card" style={{ textAlign: 'center', padding: 40 }}>
          <Sparkles size={32} color="var(--pi-sapphire)" style={{ margin: '0 auto 12px', animation: 'pi-fade-in 0.6s ease-in-out infinite alternate' }} />
          <p style={{ fontSize: '0.9rem', color: 'var(--pi-text-muted)' }}>Generating report with AI...</p>
        </div>
      )}

      {selectedReport && !generating && (
        <div className="phoenix-card">
          <h3 style={{ fontSize: '1rem', fontWeight: 700, color: 'var(--pi-text)', marginBottom: 16 }}>Generated Report Preview</h3>
          <div style={{ whiteSpace: 'pre-wrap', fontSize: '0.95rem', color: 'var(--pi-text-secondary)', lineHeight: 1.7 }}>
            {SAMPLE_IOTD.split('**').map((part, i) => (
              i % 2 === 0
                ? <span key={i}>{part}</span>
                : <strong key={i} style={{ color: 'var(--pi-text)' }}>{part}</strong>
            ))}
          </div>
        </div>
      )}

      {insight && <div style={{ marginTop: 20 }}><AIInsightCard>{insight.text}</AIInsightCard></div>}
    </PhoenixPage>
  );
}
