'use client';

import { useState } from 'react';
import { PhoenixPage } from '@/components/demos/phoenix-intel/PhoenixPage';
import { AIInsightCard } from '@/components/demos/phoenix-intel/AIInsightCard';
import { getInsight } from '@/data/phoenix-intel/ai-insights';
import { FileText, Sparkles, Clock } from 'lucide-react';

const REPORT_TYPES = [
  { id: 'iotd', name: "President's Intelligence of the Day", description: 'AI-generated daily briefing — replaces Natalie\'s manual "Items of the Day" email to President', frequency: 'Daily', lastGenerated: '2026-03-16', views: 22 },
  { id: 'monthly', name: 'Monthly Performance Report', description: 'Revenue, utilization, engagement progress, and financial projections', frequency: 'Monthly', lastGenerated: '2026-03-01', views: 8 },
  { id: 'pipeline', name: 'Pipeline Analysis Report', description: 'Deal stage analysis, conversion rates, and revenue forecasting', frequency: 'Weekly', lastGenerated: '2026-03-14', views: 12 },
  { id: 'client-health', name: 'Client Health Summary', description: 'Health scores, engagement status, and renewal opportunities', frequency: 'Monthly', lastGenerated: '2026-03-01', views: 6 },
  { id: 'assessment', name: 'Assessment Portfolio Report', description: 'Completed assessments, trends, and cross-client insights', frequency: 'Quarterly', lastGenerated: '2026-01-15', views: 4 },
  { id: 'training', name: 'Academy Analytics Report', description: 'Enrollment, completion rates, satisfaction scores, and revenue', frequency: 'Monthly', lastGenerated: '2026-03-01', views: 5 },
];

const REPORT_CONTENT: Record<string, string> = {
  iotd: `**President's Intelligence of the Day — ${new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}**

**Pipeline:**
- Mountain View Phase 2 ($95K) — contract signing expected today
- Green Valley ($85K) — proposal sent 6 days ago, follow-up recommended
- SafeHaven ($58K) — final scope meeting scheduled for March 20

**Client Health:**
- Heritage Arts (assessment 88% complete) — transition to renewal within 30 days
- Faith & Light (stewardship 82%) — approaching final deliverables

**Financial:**
- Q1 revenue: $246K (strongest quarter ever)
- YTD target tracking: 93% ($840K of $900K)

**Action Items:**
1. Call Green Valley — 6 days without follow-up on $85K proposal
2. Schedule Phase 2 kickoff with Mountain View after signing
3. Begin renewal conversation with Heritage Arts

*Generated by Phoenix Intel AI*`,

  monthly: `**Monthly Performance Report — ${new Date().toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}**

**Revenue Summary:**
- Month revenue: $92K (target: $75K — 123% attainment)
- YTD revenue: $246K ($900K annual target — 27% through year, 25% through calendar)
- Top service line: Campaign Readiness ($38K)

**Utilization:**
- Team average: 78% (target: 75%)
- Highest: Sarah Kim (92%) — monitor for burnout risk
- Lowest: Thomas Park (65%) — capacity available for new engagements

**Engagement Health:**
- 5 active engagements, 3 green, 1 yellow (Heritage Arts — scope creep), 1 red (Faith & Light — behind on deliverables)
- 2 engagements approaching renewal window (Heritage Arts, Hope Springs)

**Projections:**
- Q2 forecast: $210K (based on pipeline conversion + active engagements)
- Annual projection: $870K (3.3% below $900K target — recoverable with Mountain View close)

*Generated by Phoenix Intel AI*`,

  pipeline: `**Pipeline Analysis — Week of ${new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}**

**Stage Summary:**
- Inquiry: 2 deals ($45K)
- Qualified: 1 deal ($42K)
- Proposal Sent: 1 deal ($85K)
- Negotiation: 2 deals ($153K)
- Total weighted pipeline: $198K

**Conversion Rates (trailing 12 months):**
- Inquiry → Qualified: 60%
- Qualified → Proposal: 75%
- Proposal → Close: 68%
- Overall win rate: 31% (industry avg: 22%)

**Velocity:**
- Avg days to close: 57 days (down from 72 days last year)
- Fastest close: Mountain View Academy (34 days — strong referral)
- Slowest active: Green Valley (42 days in Proposal stage)

**Recommendations:**
1. Green Valley follow-up overdue — 6 days without contact on $85K proposal
2. SafeHaven meeting on March 20 is make-or-break — prepare board presentation
3. Two inquiry-stage prospects need qualification calls this week

*Generated by Phoenix Intel AI*`,

  'client-health': `**Client Health Summary — ${new Date().toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}**

**Portfolio Overview:**
- 5 active clients, 12 total in system
- Average health score: 82/100
- Net Promoter Score: 72 (excellent for consulting)

**Green (3 clients):**
- Mountain View Academy — Campaign on track, 75% through deliverables, strong board engagement
- Hope Springs Foundation — Feasibility study proceeding well, 6 of 8 deliverables complete
- Riverside Health Alliance — Planned giving launch successful, exceeding gift targets by 15%

**Yellow (1 client):**
- Heritage Arts Collective — Assessment 88% complete but scope expanding. Lead consultant flagged additional board interviews needed. Budget impact: +$8K estimated.

**Red (1 client):**
- Faith & Light Fellowship — Stewardship program behind schedule (82% vs 95% target). Root cause: client-side staff turnover delayed data gathering. Mitigation: extended timeline by 30 days.

**Renewal Opportunities:**
- Heritage Arts — engagement ends Q2, renewal conversation recommended within 30 days
- Hope Springs — engagement ends Q3, client has expressed interest in Phase 2

*Generated by Phoenix Intel AI*`,

  assessment: `**Assessment Portfolio Report — Q1 2026**

**Completed Assessments:**
- 8 assessments completed this quarter (vs 6 same quarter last year)
- Average score: 74/100 (indicating significant room for improvement — good for engagement conversion)
- Most common gap: Donor stewardship systems (avg 2.1/5 across all clients)

**Assessment Types:**
- Fundraising Maturity: 4 completed (avg score: 71)
- Board Engagement: 2 completed (avg score: 78)
- Campaign Readiness: 2 completed (avg score: 73)

**Cross-Client Insights:**
- Organizations with boards scoring >80 on engagement have 2.3x higher campaign success rates
- Planned giving readiness is the weakest dimension across all clients (avg 1.8/5)
- Organizations investing in donor CRM systems score 25% higher on stewardship

**Conversion:**
- 6 of 8 assessment clients converted to full engagements (75% conversion rate)
- Average engagement value from assessment leads: $52K

*Generated by Phoenix Intel AI*`,

  training: `**Academy Analytics Report — ${new Date().toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}**

**Enrollment & Completion:**
- Total enrollments: 342 (up 18% MoM)
- Completion rate: 78% (target: 75%)
- Certificates issued: 156
- Average satisfaction: 4.6/5

**Top Courses:**
1. Board Fundraising Fundamentals — 89 enrollments, 4.8/5 rating
2. Major Gift Officer Certification — 45 enrollments, 4.7/5 rating
3. Annual Fund Best Practices — 67 enrollments, 4.5/5 rating
4. Campaign Leadership — 34 enrollments, 4.9/5 rating

**Revenue:**
- Course revenue: $28K this month
- Org license revenue: $12K (5 active licenses)
- YTD total: $94K (target: $120K annual)

**Content Pipeline:**
- 3 new courses in development (Planned Giving Essentials, Data-Driven Fundraising, Nonprofit Governance)
- 2 courses being updated (Board Engagement, Stewardship Systems)

*Generated by Phoenix Intel AI*`,
};

export default function ReportsPage() {
  const insight = getInsight('reports');
  const [selectedReport, setSelectedReport] = useState<string | null>(null);
  const [generating, setGenerating] = useState(false);

  const handleGenerate = (reportId: string) => {
    setGenerating(true);
    setSelectedReport(null);
    setTimeout(() => {
      setSelectedReport(reportId);
      setGenerating(false);
    }, 1500);
  };

  return (
    <PhoenixPage title="Reports" subtitle="AI-generated intelligence reports — replacing Kelly's 3 manual reports" accentColor="#3b6bf5">
      {/* Manual Process Pain Point */}
      <div className="phoenix-card" style={{ marginBottom: 20, borderLeft: '3px solid #ef4444' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 6 }}>
          <span className="pi-label" style={{ color: '#ef4444' }}>Current State: Manual Report Production</span>
        </div>
        <p className="pi-body-muted" style={{ marginBottom: 8 }}>
          Kelly (Director of Client Services) maintains proposal tracking grids, Gantt charts, client total contracts, and Strategic Plan Metrics — all in Excel with manual copy-paste between linked workbooks. Cassandra (Business Manager) compiles P&amp;L and balance sheets in QuickBooks, then manually formats transaction lists by client/state in Excel for CPA upload. The &ldquo;game of telephone&rdquo; effect spans 8-9 tracking locations.
        </p>
        <div style={{ display: 'flex', gap: 6, flexWrap: 'wrap', marginBottom: 8 }}>
          {[
            'Proposal Tracking Grid (Excel)',
            'Gantt Charts (Excel)',
            'Client Total Contracts (Excel)',
            'Strategic Plan Metrics (Excel)',
            'Projections Comparison (Excel)',
            'Satisfaction Surveys (Formsite)',
          ].map(r => (
            <span key={r} className="pi-badge" style={{
              background: '#ef444420', color: '#ef4444',
            }}>{r}</span>
          ))}
        </div>
        <div className="pi-caption" style={{
          padding: '8px 12px', borderRadius: 6, background: '#7c3aed08', border: '1px solid #7c3aed20',
        }}>
          <strong style={{ color: '#7c3aed' }}>Items of the Day (IoTD):</strong> Natalie (Executive Coordinator) currently sends a daily manual email to the President outlining meetings, tasks, project updates, travel, presentations, and action items. The AI-generated IoTD replaces this with real-time data.
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-8">
        {REPORT_TYPES.map(report => (
          <div key={report.id} className="phoenix-card">
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 8 }}>
              <div style={{ display: 'flex', gap: 10 }}>
                <FileText size={18} color="var(--pi-sapphire)" />
                <div>
                  <div className="pi-label">{report.name}</div>
                  <div className="pi-body-muted" style={{ marginTop: 2 }}>{report.description}</div>
                </div>
              </div>
            </div>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginTop: 12, paddingTop: 8, borderTop: '1px solid var(--pi-border-faint)' }}>
              <div className="pi-caption" style={{ display: 'flex', gap: 12 }}>
                <span><Clock size={10} style={{ display: 'inline', verticalAlign: 'middle' }} /> {report.frequency}</span>
                <span>Last: {report.lastGenerated}</span>
                <span>{report.views} views</span>
              </div>
              <button
                onClick={() => handleGenerate(report.id)}
                className="phoenix-btn"
                style={{
                  padding: '6px 12px', background: 'var(--pi-sapphire)',
                  color: '#fff', display: 'flex', alignItems: 'center', gap: 4,
                }}
              >
                <Sparkles size={12} /> Generate
              </button>
            </div>
          </div>
        ))}
      </div>

      {generating && (
        <div className="phoenix-card" style={{ textAlign: 'center', padding: 40 }}>
          <Sparkles size={32} color="var(--pi-sapphire)" style={{ margin: '0 auto 12px', animation: 'pi-fade-in 0.6s ease-in-out infinite alternate' }} />
          <p className="pi-body-muted">Generating report with AI...</p>
        </div>
      )}

      {selectedReport && !generating && (
        <div className="phoenix-card">
          <h3 className="pi-section-title">Generated Report Preview</h3>
          <div className="pi-body" style={{ whiteSpace: 'pre-wrap', color: 'var(--pi-text-secondary)', lineHeight: 1.7 }}>
            {REPORT_CONTENT[selectedReport!].split('**').map((part, i) => (
              i % 2 === 0
                ? <span key={i}>{part}</span>
                : <strong key={i} style={{ color: 'var(--pi-text)' }}>{part}</strong>
            ))}
          </div>
        </div>
      )}

      {insight && <div style={{ marginTop: 20 }}><AIInsightCard>{insight.text}</AIInsightCard></div>}
    </PhoenixPage>
  );
}
