// AUTO-GENERATED by scripts/generate-registry.ts — DO NOT EDIT
export interface DemoRegistryEntry {
  name: string;
  slug: string;
  industry: string;
  tagline: string;
  color: string;
  layout: string;
  badge?: string;
  externalUrl?: string;
}

export const demoRegistry: DemoRegistryEntry[] = [
  {
    "name": "AEGIS",
    "slug": "aegis",
    "industry": "Crisis Management",
    "tagline": "Privilege-first crisis defense for law firms and corporate counsel",
    "color": "#D4A574",
    "layout": "sidebar",
    "badge": "Interactive Demo"
  },
  {
    "name": "CHARTER",
    "slug": "charter",
    "industry": "Credit Unions",
    "tagline": "Member-owned financial intelligence for community institutions",
    "color": "#B8976A",
    "layout": "sidebar",
    "badge": "Interactive Demo"
  },
  {
    "name": "CRESTLINE SPM",
    "slug": "crestline",
    "industry": "Department Store Retail",
    "tagline": "Premium retail compensation for multi-format department stores",
    "color": "#c9a84c",
    "layout": "sidebar",
    "badge": "Interactive Demo"
  },
  {
    "name": "EQUIPR",
    "slug": "equipr",
    "industry": "Equipment Rental",
    "tagline": "AI-powered fleet intelligence and utilization analytics for rental operations",
    "color": "#E87040",
    "layout": "sidebar",
    "badge": "ARA Show 2026"
  },
  {
    "name": "MERIDIAN",
    "slug": "meridian",
    "industry": "Private Equity",
    "tagline": "Carried interest compensation and fund waterfall for M&A-focused PE firms",
    "color": "#3B82F6",
    "layout": "sidebar",
    "badge": "Interactive Demo"
  },
  {
    "name": "Sales Governance Manager (SGM)",
    "slug": "prizym-governance",
    "industry": "Sales Performance Management",
    "tagline": "Sales Governance Manager (SGM) — part of the Prizym Sales Planning Suite",
    "color": "#0ea5e9",
    "layout": "sidebar",
    "badge": "Interactive Demo"
  },
  {
    "name": "Prizym SQM — Sales Quota Manager",
    "slug": "quota",
    "industry": "Sales Performance Management",
    "tagline": "Sales quota planning and attainment for the modern CRO",
    "color": "#f59e0b",
    "layout": "topnav",
    "badge": "Demo Data"
  },
  {
    "name": "REGISTER",
    "slug": "register",
    "industry": "Retail Operations",
    "tagline": "Retail revenue intelligence from floor to boardroom — comp, scheduling, analytics",
    "color": "#8BA3BE",
    "layout": "sidebar",
    "badge": "Interactive Demo"
  },
  {
    "name": "RIDGELINE",
    "slug": "ridgeline",
    "industry": "Specialty Trade Distribution",
    "tagline": "RevOps & SPM for specialty trade distribution — territory, comp, branch operations",
    "color": "#5B8CB8",
    "layout": "sidebar",
    "badge": "Interactive Demo"
  },
  {
    "name": "ROUTEIQ",
    "slug": "routeiq",
    "industry": "Beverage Distribution",
    "tagline": "Revenue operating system for multi-state F&B distribution — organized by failure points, not tools",
    "color": "#4338CA",
    "layout": "sidebar",
    "badge": "Interactive Demo"
  },
  {
    "name": "STEEPLE",
    "slug": "steeple",
    "industry": "Church Management",
    "tagline": "Full-spectrum church management and ministry platform",
    "color": "#8b5cf6",
    "layout": "sidebar",
    "badge": "Interactive Demo"
  },
  {
    "name": "Prizym SWIC — Sales What-If Calculator",
    "slug": "swic",
    "industry": "Sales Performance Management",
    "tagline": "Interactive what-if scenario modeling for sales compensation — test changes before they go live",
    "color": "#10b981",
    "layout": "focus",
    "badge": "Live Demo",
    "externalUrl": "https://demo.swic-summit.aicoderally.com"
  },
  {
    "name": "WELLSPRING",
    "slug": "wellspring",
    "industry": "Oil & Gas",
    "tagline": "Field operations intelligence for upstream oil and gas producers",
    "color": "#D97706",
    "layout": "sidebar",
    "badge": "Interactive Demo"
  }
];
