// AUTO-GENERATED by scripts/generate-registry.ts — DO NOT EDIT
export interface DemoRegistryEntry {
  name: string;
  slug: string;
  industry: string;
  tagline: string;
  color: string;
  layout: string;
}

export const demoRegistry: DemoRegistryEntry[] = [
  {
    "name": "AEGIS",
    "slug": "aegis",
    "industry": "Crisis Management",
    "tagline": "Privilege-first crisis defense for law firms and corporate counsel",
    "color": "#D4A574",
    "layout": "sidebar"
  },
  {
    "name": "CHARTER",
    "slug": "charter",
    "industry": "Credit Unions",
    "tagline": "Member-owned financial intelligence for community institutions",
    "color": "#8B7355",
    "layout": "sidebar"
  },
  {
    "name": "CRESTLINE SPM",
    "slug": "crestline",
    "industry": "Department Store Retail",
    "tagline": "Premium retail compensation for multi-format department stores",
    "color": "#c9a84c",
    "layout": "sidebar"
  },
  {
    "name": "EQUIPR",
    "slug": "equipr",
    "industry": "Equipment Rental",
    "tagline": "AI-powered fleet intelligence and utilization analytics for rental operations",
    "color": "#F59E0B",
    "layout": "sidebar"
  },
  {
    "name": "MERIDIAN",
    "slug": "meridian",
    "industry": "Private Equity",
    "tagline": "Carried interest compensation and fund waterfall for M&A-focused PE firms",
    "color": "#D4A847",
    "layout": "sidebar"
  },
  {
    "name": "Prizym SGM — Sales Governance Manager",
    "slug": "prizym-governance",
    "industry": "Sales Performance Management",
    "tagline": "Enterprise governance platform for sales compensation programs — policies, plans, approvals, and audit trails",
    "color": "#06b6d4",
    "layout": "sidebar"
  },
  {
    "name": "ROUTEIQ",
    "slug": "routeiq",
    "industry": "Beverage Distribution",
    "tagline": "Revenue operating system for beverage distributors — territory, comp, route ops",
    "color": "#C6A052",
    "layout": "sidebar"
  },
  {
    "name": "Prizym SQM — Sales Quota Manager",
    "slug": "quota",
    "industry": "Sales Performance Management",
    "tagline": "Sales quota planning and attainment for the modern CRO",
    "color": "#f59e0b",
    "layout": "topnav"
  },
  {
    "name": "REGISTER",
    "slug": "register",
    "industry": "Retail Operations",
    "tagline": "Retail revenue intelligence from floor to boardroom — comp, scheduling, analytics",
    "color": "#64748B",
    "layout": "sidebar"
  },
  {
    "name": "RIDGELINE",
    "slug": "ridgeline",
    "industry": "Specialty Trade Distribution",
    "tagline": "RevOps & SPM for specialty trade distribution — territory, comp, branch operations",
    "color": "#1E3A5F",
    "layout": "sidebar"
  },
  {
    "name": "STEEPLE",
    "slug": "steeple",
    "industry": "Church Management",
    "tagline": "Full-spectrum church management and ministry platform",
    "color": "#8b5cf6",
    "layout": "sidebar"
  },
  {
    "name": "WELLSPRING",
    "slug": "wellspring",
    "industry": "Oil & Gas",
    "tagline": "Field operations intelligence for upstream oil and gas producers",
    "color": "#B45309",
    "layout": "sidebar"
  }
];
