/**
 * Build-time script: scans all demo.config.ts files, extracts meta,
 * and generates data/demo-registry.ts for the home page.
 *
 * Usage: tsx scripts/generate-registry.ts [--json] [--help]
 */
import * as fs from 'fs';
import * as path from 'path';

const DEMOS_DIR = path.resolve(__dirname, '../app/(demos)');
const OUTPUT_FILE = path.resolve(__dirname, '../data/demo-registry.ts');

interface RegistryEntry {
  name: string;
  slug: string;
  industry: string;
  tagline: string;
  color: string;
  layout: string;
  badge?: string;
  externalUrl?: string;
}

async function main() {
  if (process.argv.includes('--help')) {
    console.log(`generate-registry: Scans demo.config.ts files and generates data/demo-registry.ts

Usage: tsx scripts/generate-registry.ts [--json] [--help]

Options:
  --json   Output as JSON instead of writing the registry file
  --help   Show this help message

Examples:
  tsx scripts/generate-registry.ts
  tsx scripts/generate-registry.ts --json`);
    process.exit(0);
  }

  const dirs = fs.readdirSync(DEMOS_DIR, { withFileTypes: true })
    .filter(d => d.isDirectory())
    .map(d => d.name)
    .sort();

  const entries: RegistryEntry[] = [];
  const errors: string[] = [];

  for (const dir of dirs) {
    const configPath = path.join(DEMOS_DIR, dir, 'demo.config.ts');
    if (!fs.existsSync(configPath)) continue;

    try {
      const mod = await import(configPath);
      const config = mod.default;

      if (!config) {
        errors.push(`${dir}: no default export in demo.config.ts`);
        continue;
      }

      if (config.slug && config.slug !== dir) {
        errors.push(`${dir}: slug '${config.slug}' does not match directory name '${dir}'`);
        continue;
      }

      if (!config.meta?.industry) {
        errors.push(`${dir}: missing meta.industry (required for registry)`);
        continue;
      }
      if (!config.meta?.tagline) {
        errors.push(`${dir}: missing meta.tagline (required for registry)`);
        continue;
      }

      entries.push({
        name: config.product?.name ?? dir.toUpperCase(),
        slug: config.slug ?? dir,
        industry: config.meta.industry,
        tagline: config.meta.tagline,
        color: config.meta.color ?? config.colors?.primary ?? '#6B7280',
        layout: config.layout ?? 'sidebar',
        badge: config.product?.badge,
        externalUrl: config.meta?.externalUrl,
      });
    } catch (err) {
      errors.push(`${dir}: failed to import — ${err}`);
    }
  }

  if (errors.length > 0) {
    console.error('Registry generation errors:');
    errors.forEach(e => console.error(`  ✗ ${e}`));
    process.exit(1);
  }

  if (process.argv.includes('--json')) {
    console.log(JSON.stringify(entries, null, 2));
    process.exit(0);
  }

  const output = `// AUTO-GENERATED by scripts/generate-registry.ts — DO NOT EDIT
export interface DemoRegistryEntry {
  name: string;
  slug: string;
  industry: string;
  tagline: string;
  color: string;
  layout: string;
  badge?: string;
  externalUrl?: string;
}

export const demoRegistry: DemoRegistryEntry[] = ${JSON.stringify(entries, null, 2)};
`;

  fs.mkdirSync(path.dirname(OUTPUT_FILE), { recursive: true });
  fs.writeFileSync(OUTPUT_FILE, output);
  console.log(`✓ Generated registry with ${entries.length} demos → ${path.relative(process.cwd(), OUTPUT_FILE)}`);
  process.exit(0);
}

main().catch(err => {
  console.error('Fatal:', err);
  process.exit(1);
});
